In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("../data/player_stats.csv")

active_df = df[df["isActive"] == 1]
active_df.sort_values("total points", ascending=False)

,name,rating,value,total points,goals,assist,minutes played,isActive,average points,team,man of match,position,goals conceded,yellow cards,red cards,penalties earned,balls recovered
72,D. Szoboszlai,4.0,6.9,83,5,4,885,1,8.3,LIV,2,midfielders,0,1,0,1,47
0,K. Mbappé,0.5,11.1,82,13,1,732,1,9.1,RMA,3,attackers,0,2,0,0,4
24,K. Kvaratskhelia,2.0,8.2,82,7,4,704,1,7.5,PSG,3,midfielders,0,2,0,1,16
46,Vitinha,3.0,7.3,81,6,1,1079,1,6.8,PSG,1,midfielders,0,0,0,0,61
6,Vinícius Júnior,4.5,9.6,78,5,7,990,1,6.5,RMA,2,midfielders,0,2,0,1,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,Javier Navarro,0.0,4.0,0,0,0,0,1,0.0,RMA,0,goal keepers,0,0,0,0,0
995,Á. Pécsi,0.0,4.0,0,0,0,0,1,0.0,LIV,0,goal keepers,0,0,0,0,0
1054,Bruno Ramos,0.0,4.0,0,0,0,0,1,0.0,SPO,0,defenders,0,0,0,0,0
1071,Diego Aguado,0.0,4.0,0,0,0,0,1,0.0,RMA,0,defenders,0,0,0,0,0
443,O. Vargas,0.0,5.0,0,0,0,0,1,0.0,ATM,0,midfielders,0,0,0,0,0

In [55]:
points_by_position = df.groupby("position")["total points"].sum()
points_by_position.sort_values(ascending=False)

position
midfielders     7528
defenders       6145
attackers       2836
goal keepers    1189
Name: total points, dtype: int64

In [57]:
players_per_position = df.groupby("position")["name"].count().reset_index()
players_per_position.columns = ["position", "player_count"]
players_per_position.sort_values("player_count", ascending=False)

       position  player_count
3   midfielders           469
1     defenders           401
0     attackers           202
2  goal keepers           144

In [64]:
# Total points by position and team
points_by_pos_team = active_df.groupby(["position", "team"])["total points"].sum().reset_index()

# Filter to just midfielders
midfielders = points_by_pos_team[points_by_pos_team["position"] == "midfielders"]
midfielders.sort_values("total points", ascending=False)

       position team  total points
30  midfielders  PSG           399
31  midfielders  RMA           374
24  midfielders  ARS           311
28  midfielders  LIV           297
26  midfielders  BAR           252
25  midfielders  ATM           248
27  midfielders  BAY           248
32  midfielders  SPO           224
29  midfielders  MAR             0

In [65]:
attackers = points_by_pos_team[points_by_pos_team["position"] == "attackers"]
attackers.sort_values("total points", ascending=False)

    position team  total points
1  attackers  ATM           160
3  attackers  BAY           141
2  attackers  BAR            99
6  attackers  RMA            91
0  attackers  ARS            73
4  attackers  LIV            71
7  attackers  SPO            54
5  attackers  PSG            39

In [66]:
defenders = points_by_pos_team[points_by_pos_team["position"] == "defenders"]
defenders.sort_values("total points", ascending=False)

     position team  total points
8   defenders  ARS           244
13  defenders  PSG           240
12  defenders  LIV           237
15  defenders  SPO           206
14  defenders  RMA           182
11  defenders  BAY           169
9   defenders  ATM           164
10  defenders  BAR           142

In [67]:
keepers = points_by_pos_team[points_by_pos_team["position"] == "goal keepers"]
keepers.sort_values("total points", ascending=False)

        position team  total points
22  goal keepers  RMA            59
16  goal keepers  ARS            47
20  goal keepers  LIV            40
19  goal keepers  BAY            39
21  goal keepers  PSG            34
23  goal keepers  SPO            31
17  goal keepers  ATM            28
18  goal keepers  BAR            22

In [68]:
top10_by_position = (
    active_df
    .sort_values("total points", ascending=False)
    .groupby("position")
    .head(10)
    [["position", "name", "team", "total points"]]
    .sort_values(["position", "total points"], ascending=[True, False])
)

top10_by_position[top10_by_position["position"] == "midfielders"]

        position               name team  total points
72   midfielders      D. Szoboszlai  LIV            83
24   midfielders   K. Kvaratskhelia  PSG            82
46   midfielders            Vitinha  PSG            81
6    midfielders    Vinícius Júnior  RMA            78
91   midfielders  Francisco Trincão  SPO            69
81   midfielders       Fermín López  BAR            67
77   midfielders        F. Valverde  RMA            66
33   midfielders      G. Martinelli  ARS            57
22   midfielders           M. Olise  BAY            57
115  midfielders      A. Tchouaméni  RMA            54

In [69]:
top10_by_position = (
    active_df
    .sort_values("total points", ascending=False)
    .groupby("position")
    .head(10)
    [["position", "name", "team", "total points"]]
    .sort_values(["position", "total points"], ascending=[True, False])
)

top10_by_position[top10_by_position["position"] == "attackers"]

      position          name team  total points
0    attackers     K. Mbappé  RMA            82
12   attackers    J. Alvarez  ATM            75
1    attackers       H. Kane  BAY            71
43   attackers   M. Rashford  BAR            50
500  attackers   Luis Suárez  SPO            44
35   attackers    A. Sørloth  ATM            44
17   attackers  A. Griezmann  ATM            41
14   attackers   V. Gyökeres  ARS            41
36   attackers     Luis Díaz  BAY            38
28   attackers    H. Ekitike  LIV            36

In [86]:
top10_by_position = (
    # active_df
    active_df[active_df["team"] == "ARS"]
    .sort_values("total points", ascending=False)
    .groupby("position")
    .head(10)
    [["position", "name", "team", "total points", "goals conceded"]]
    .sort_values(["position", "total points"], ascending=[True, False])
)

top10_by_position[top10_by_position["position"] == "defenders"]

      position             name team  total points  goals conceded
223  defenders          Gabriel  ARS            50               1
203  defenders        W. Saliba  ARS            39               3
507  defenders        J. Timber  ARS            38               3
624  defenders  M. Lewis-Skelly  ARS            33               4
570  defenders      P. Hincapie  ARS            27               2
647  defenders         B. White  ARS            23               2
850  defenders      C. Mosquera  ARS            21               4
652  defenders     R. Calafiori  ARS            13               1

In [76]:
top10_by_position = (
    active_df
    .sort_values("total points", ascending=False)
    .groupby("position")
    .head(10)
    [["position", "name", "team", "total points"]]
    .sort_values(["position", "total points"], ascending=[True, False])
)

top10_by_position[top10_by_position["position"] == "goal keepers"]

         position            name team  total points
145  goal keepers     T. Courtois  RMA            55
249  goal keepers         D. Raya  ARS            46
593  goal keepers       Rui Silva  SPO            28
191  goal keepers  Alisson Becker  LIV            28
182  goal keepers        M. Neuer  BAY            26
207  goal keepers        J. Oblak  ATM            22
810  goal keepers      M. Safonov  PSG            21
808  goal keepers     Joan Garcia  BAR            15
689  goal keepers        J. Urbig  BAY            13
811  goal keepers    L. Chevalier  PSG            13